const testimonialData = [
    {
        id: 1,
        customer_name: "Arun Kumar",
        role: "Software Engineer",
        company: "TechNova Solutions",
        rating: "5",
        photo_url: "https://randomuser.me/api/portraits/men/1.jpg",
        testimonial: "Excellent service and amazing support throughout the project execution.",
        isFeatured: true,
        status: "Published",
        created_at:"12/11/2023",
        updated_at:"12/11/2023"
    },
    {
        id: 2,
        customer_name: "Priya Sharma",
        role: "Project Manager",
        company: "Skyline Technologies",
        rating: "4",
        photo_url: "https://randomuser.me/api/portraits/women/2.jpg",
        testimonial: "The team delivered high-quality results on time with great professionalism.",
        isFeatured: false,
        status: "Published",
        created_at:"12/11/2023",
        updated_at:"12/11/2023"
    },
    {
        id: 3,
        customer_name: "Rahul Verma",
        role: "Business Analyst",
        company: "DataCraft Pvt Ltd",
        rating: "5",
        photo_url: "https://randomuser.me/api/portraits/men/3.jpg",
        testimonial: "Very smooth experience working with the company. Highly recommended.",
        isFeatured: true,
        status: "Draft",
        created_at:"12/11/2023",
        updated_at:"12/11/2023"
    },
    {
        id: 4,
        customer_name: "Sneha Reddy",
        role: "UI/UX Designer",
        company: "PixelForge Studio",
        rating: "4",
        photo_url: "https://randomuser.me/api/portraits/women/4.jpg",
        testimonial: "Creative approach and excellent communication during the project.",
        isFeatured: false,
        status: "Published",
        created_at:"12/11/2023",
        updated_at:"12/11/2023"
    },
    {
        id: 5,
        customer_name: "Karthik Raj",
        role: "Marketing Lead",
        company: "BrandHive Media",
        rating: "5",
        photo_url: "https://randomuser.me/api/portraits/men/5.jpg",
        testimonial: "One of the best collaborations we’ve had in recent years.",
        isFeatured: true,
        status: "Published",
        created_at:"12/11/2023",
        updated_at:"12/11/2023"
    },
    {
        id: 6,
        customer_name: "Meera Nair",
        role: "HR Manager",
        company: "PeopleFirst Corp",
        rating: "4",
        photo_url: "https://randomuser.me/api/portraits/women/6.jpg",
        testimonial: "Professional and efficient service from start to finish.",
        isFeatured: false,
        status: "Archived",
        created_at:"12/11/2023",
        updated_at:"12/11/2023"
    },
    {
        id: 7,
        customer_name: "Vikram Singh",
        role: "Operations Head",
        company: "LogiTrack Systems",
        rating: "5",
        photo_url: "https://randomuser.me/api/portraits/men/7.jpg",
        testimonial: "Outstanding quality and timely delivery exceeded our expectations.",
        isFeatured: true,
        status: "Published",
        created_at:"12/11/2023",
        updated_at:"12/11/2023"
    },
    {
        id: 8,
        customer_name: "Ananya Patel",
        role: "Content Strategist",
        company: "Creative Minds Agency",
        rating: "4",
        photo_url: "https://randomuser.me/api/portraits/women/8.jpg",
        testimonial: "Very satisfied with the support and responsiveness of the team.",
        isFeatured: false,
        status: "Draft",
        created_at:"12/11/2023",
        updated_at:"12/11/2023"
    },
    {
        id: 9,
        customer_name: "Rohit Mehta",
        role: "CEO",
        company: "Innovexa Labs",
        rating: "5",
        photo_url: "https://randomuser.me/api/portraits/men/9.jpg",
        testimonial: "Fantastic experience. The project was handled with great expertise.",
        isFeatured: true,
        status: "Published",
        created_at:"12/11/2023",
        updated_at:"12/11/2023"
    },
    {
        id: 10,
        customer_name: "Divya Iyer",
        role: "Product Owner",
        company: "NextGen Apps",
        rating: "4",
        photo_url: "https://randomuser.me/api/portraits/women/10.jpg",
        testimonial: "Reliable team with excellent technical and communication skills.",
        isFeatured: false,
        status: "Archived",
        created_at:"12/11/2023",
        updated_at:"12/11/2023"
    }
];

export default testimonialData;